// message schema file

const mongoose = require('mongoose');
// const variable named mongoose
// require() used to import modules, loads the mongoose npm package

// messageSchema holds the blueprint for the message schema
const messageSchema = new mongoose.Schema({

    // define fields for the sender
    sender : {
        type : mongoose.Schema.Types.ObjectId, // this entire line says - The value for this particular field in my schema should be a reference to a MongoDB ObjectId
        // ObjectIds are the unique primary keys automatically generated by MongoDB for each document.

        ref : 'User', // references the user model, to know who sent the message
        // The ID number being put here for the sender belongs to someone in the 'User' list
        // If we ever need to know more about this sender, we can look up this ID number in the 'User' list.

        required : true // validation rule, every message document must have a sender value
        // basically, every message MUST say who sent it, it cannot be left blank
    },

    text : {
        type : String,
        required : true // validation rule, every message document must have a text value
    },

    timestamp : {
        type : Date,
        default : Date.now 
    }
});

module.exports = mongoose.model('Message', messageSchema); // export current module so it can be used by other modules